name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - name: Angular Deploy gh-pages Actions
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
        with:
          github_access_token: ${{ secrets.DEPLOY_TOKEN }}
          build_configuration: production
          base_href: /AngularPR/
          deploy_branch: gh-pages
          angular_dist_build_folder: dist/AngularPR
        env:
          WEATHER_APP_ID: ${{ secrets.WEATHER_APP_ID }}
